- name: Install nftables
  package:
    name:
      - nftables
      - iptables
    state: present

- name: Enable nftables service
  service:
    name: nftables
    state: started
    enabled: yes

- name: Template nftables configuration
  template:
    src: "{{ nftables_config }}"
    dest: /etc/nftables.conf
  notify: Reload nftables configuration
